services:
  appointments-app:
    image: ${DOCKER_IMAGE}
    container_name: clinic-backend
    ports:
      - "8080:8080"
    restart: always
    environment:
      # Conexión a BD
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # Usuario creado por default
      COORDINATOR_EMAIL: ${COORDINATOR_EMAIL}
      COORDINATOR_PASSWORD: ${COORDINATOR_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"